# Generated by Django 4.2.6 on 2023-10-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='index/img')),
            ],
        ),
    ]
