# Generated by Django 4.2.6 on 2023-11-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='Remot/img')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='bio',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.ImageField(upload_to='Video/img'),
        ),
    ]
